### PR TITLE
Mute switch on iOS, silent when app goes in background on android

### PR DESCRIPTION
**Pull request by MartinDomig**
My fork is a collection based upon the commits of others, as well as some fixes of mine. These are:

- Use the correct sound stream ID when playing sound on iOS, so that other apps playing music won't go silent and the mute switch on iOS is working
- Don't restart a loop on android when the app is in background

### CODE REVIEW

**Comment by kaansoral** [comment]
Thanks a lot for preparing this, hope it gets merged

Indeed the first one is a real major issue

**Comment by EWBears** [comment]
@floatinghotpot please merge this PR.   

I'm having volume issues on simple loaded audio on iOS and think that this PR may fix the issues.

**Comment by alexcbluk** [comment]
Hi MartinDomig, thank you for making the effort to create a new branch. However I am still experiencing volume issues on simple loaded audio. 

The audio sound output by the device does not reflect the sound volume of the device. E.g: Maxing out the volume level on the device and the application still plays at it's normal volume...vice versa when lowering the volume level to mute the simple audio, the output result is still the same noise level as it were before.

**Comment by EWBears** [comment]
@floatinghotpot  -  sorry to write again but I'm still hoping that you will take a few minutes to merge this PR!

@MartinDomig - thank you for taking the time to collect these fixes and create this pull request.

**Comment by danielfliegauf** [comment]
Is there a reason why all these PR's are not merged? (or is it just insufficient time/motivation the owner?)

**Pull request closed without merging**
